"""
MOC Generator — Auto-generate Map of Content index files for Obsidian vault.

Scans vault folders, reads frontmatter from .md files, and generates
_Index.md files per folder with wikilinks and 1-line summaries.
Also generates a top-level _Master-Index.md linking all folder indexes.

Usage:
    python -m local_brain.scripts.moc_generator
    python -m local_brain.scripts.moc_generator --dry-run

Can also be called programmatically for targeted folder updates:
    from moc_generator import update_folder_index
    update_folder_index(vault_dir, "30-Decisions")
"""

import os
import sys
from datetime import datetime
from pathlib import Path

# --- Vault path resolution ---
from local_brain.vault_paths import vault_dir as _vault_dir

VAULT_DIR = _vault_dir()

# Folders to index (skip dotfiles, Templates, .obsidian)
SKIP_FOLDERS = {".obsidian", ".trash", "Templates", ".git", "processed"}

# Files that are never indexed (they ARE indexes)
INDEX_FILES = {"_Index.md", "_Master-Index.md", "_Wiki-Index.md", "_lint-report.md"}


def _parse_frontmatter(path: Path) -> dict[str, str]:
    """Parse YAML frontmatter from a markdown file. Simple key: value only."""
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return {}

    if not text.startswith("---"):
        return {}

    end = text.find("---", 3)
    if end < 0:
        return {}

    fm = {}
    for line in text[3:end].strip().split("\n"):
        if ":" in line:
            key, _, val = line.partition(":")
            fm[key.strip()] = val.strip()
    return fm


def _first_heading(path: Path) -> str:
    """Extract first # heading from a markdown file."""
    try:
        with open(path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith("# "):
                    return line[2:].strip()
                # Stop after first 30 lines
                if f.tell() > 5000:
                    break
    except Exception:
        pass
    return path.stem.replace("-", " ").replace("_", " ").title()


def _first_paragraph(path: Path) -> str:
    """Extract first non-heading, non-frontmatter paragraph for a summary."""
    try:
        text = path.read_text(encoding="utf-8")
    except Exception:
        return ""

    # Skip frontmatter
    if text.startswith("---"):
        end = text.find("---", 3)
        if end > 0:
            text = text[end + 3 :]

    for line in text.split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("#") or line.startswith(">") or line.startswith("---"):
            continue
        if line.startswith("*") and line.endswith("*"):
            continue
        # Found a content line
        return line[:120] + ("..." if len(line) > 120 else "")

    return ""


def scan_folder(folder: Path) -> list[tuple[Path, dict, str, str]]:
    """Scan a vault folder for .md files. Returns [(path, frontmatter, heading, summary)]."""
    results = []
    if not folder.is_dir():
        return results

    for f in sorted(folder.glob("*.md")):
        if f.name in INDEX_FILES:
            continue
        fm = _parse_frontmatter(f)
        heading = _first_heading(f)
        summary = _first_paragraph(f)
        results.append((f, fm, heading, summary))

    return results


def build_folder_index(folder_name: str, entries: list[tuple[Path, dict, str, str]]) -> str:
    """Build _Index.md content for a single vault folder."""
    today = datetime.utcnow().strftime("%Y-%m-%d")

    lines = [
        "---",
        "type: moc",
        f"date: {today}",
        "source: moc-generator",
        "aiia_managed: true",
        f"tags: [moc, {folder_name.lower().replace(' ', '-')}]",
        "---",
        "",
        f"# {folder_name}",
        "",
        "> Auto-generated index — regenerated by `brain index`.",
        "",
    ]

    # Separate AIIA-managed from hand-written
    aiia_entries = []
    manual_entries = []
    for path, fm, heading, summary in entries:
        if fm.get("aiia_managed") in ("true", "True"):
            aiia_entries.append((path, fm, heading, summary))
        else:
            manual_entries.append((path, fm, heading, summary))

    if manual_entries:
        lines.append("## Pages")
        for path, fm, heading, summary in manual_entries:
            link = f"[[{path.stem}|{heading}]]"
            date = fm.get("date", "")
            date_tag = f" ({date})" if date else ""
            if summary:
                lines.append(f"- {link}{date_tag} — {summary}")
            else:
                lines.append(f"- {link}{date_tag}")
        lines.append("")

    if aiia_entries:
        lines.append("## AIIA Generated")
        for path, fm, heading, summary in aiia_entries:
            link = f"[[{path.stem}|{heading}]]"
            date = fm.get("date", "")
            date_tag = f" ({date})" if date else ""
            lines.append(f"- {link}{date_tag}")
        lines.append("")

    lines.append(f"*{len(entries)} files · indexed {today}*")
    return "\n".join(lines)


def build_master_index(folders: dict[str, int]) -> str:
    """Build _Master-Index.md linking all folder indexes."""
    today = datetime.utcnow().strftime("%Y-%m-%d")

    lines = [
        "---",
        "type: moc",
        f"date: {today}",
        "source: moc-generator",
        "aiia_managed: true",
        "tags: [moc, master-index]",
        "---",
        "",
        "# Vault Index",
        "",
        "> Auto-generated master index — regenerated by `brain index`.",
        "",
    ]

    total_files = 0
    for folder_name in sorted(folders.keys()):
        count = folders[folder_name]
        total_files += count
        lines.append(f"- [[{folder_name}/_Index|{folder_name}]] — {count} files")

    lines.append("")
    lines.append(f"*{total_files} files across {len(folders)} folders · indexed {today}*")
    return "\n".join(lines)


def update_folder_index(vault_dir: Path, folder_name: str, dry_run: bool = False) -> bool:
    """Update _Index.md for a single folder. Returns True if written."""
    folder = vault_dir / folder_name
    if not folder.is_dir():
        return False

    entries = scan_folder(folder)
    if not entries:
        return False

    content = build_folder_index(folder_name, entries)
    dest = folder / "_Index.md"

    if dry_run:
        print(f"[dry-run] Would write {dest} ({len(content)} chars, {len(entries)} files)")
        return True

    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_suffix(".md.tmp")
    tmp.write_text(content, encoding="utf-8")
    os.rename(str(tmp), str(dest))
    print(f"Written: {folder_name}/_Index.md ({len(entries)} files)")
    return True


def run_full_index(vault_dir: Path = None, dry_run: bool = False) -> dict[str, int]:
    """Generate _Index.md for all folders and _Master-Index.md at root."""
    vault = vault_dir or VAULT_DIR
    print(f"MOC Generator — vault={vault} dry_run={dry_run}")

    folders = {}
    for item in sorted(vault.iterdir()):
        if not item.is_dir():
            continue
        if item.name in SKIP_FOLDERS or item.name.startswith("."):
            continue

        entries = scan_folder(item)
        if not entries:
            continue

        folders[item.name] = len(entries)
        content = build_folder_index(item.name, entries)
        dest = item / "_Index.md"

        if dry_run:
            print(f"[dry-run] {item.name}/_Index.md — {len(entries)} files")
        else:
            tmp = dest.with_suffix(".md.tmp")
            tmp.write_text(content, encoding="utf-8")
            os.rename(str(tmp), str(dest))
            print(f"Written: {item.name}/_Index.md ({len(entries)} files)")

    # Master index
    if folders:
        master = build_master_index(folders)
        master_path = vault / "_Master-Index.md"
        if dry_run:
            print(f"[dry-run] _Master-Index.md — {len(folders)} folders")
        else:
            tmp = master_path.with_suffix(".md.tmp")
            tmp.write_text(master, encoding="utf-8")
            os.rename(str(tmp), str(master_path))
            print(f"Written: _Master-Index.md ({len(folders)} folders)")

    print(f"\nDone: {len(folders)} folders indexed")
    return folders


def main():
    dry_run = "--dry-run" in sys.argv or "-n" in sys.argv
    run_full_index(dry_run=dry_run)


if __name__ == "__main__":
    main()
