"""
Vault Watcher — Ingest Obsidian vault changes into AIIA's knowledge base.

Closes the feedback loop: edits in Obsidian flow back into AIIA's
ChromaDB + structured memory, making the system bidirectional:

    AIIA Memory ──obsidian_bridge──> AIIAVault/
    AIIAVault/ ──vault_watcher───> AIIA Knowledge + Memory

Scans ~/AIIAVault for new/changed markdown files, skips AIIA-owned
auto-generated files, and ingests everything else via the Brain API.

Uses the same hash-based incremental sync as obsidian_bridge.py:
only processes files whose content hash has changed since last run.

Structured extraction:
- Files in 30-Decisions/ → also stored as AIIA memory (category: decisions)
- Files in 50-Stories/ → also stored as AIIA memory (category: project)
- Files in 10-Daily/ → also stored as AIIA memory (category: sessions)
- Files in 60-Clients/ → also stored as AIIA memory (category: project)
- All other .md files → ingested as knowledge docs only (ChromaDB)

Usage:
    python -m local_brain.scripts.vault_watcher
    python -m local_brain.scripts.vault_watcher --dry-run
    python -m local_brain.scripts.vault_watcher --force

Schedule:
    Nightly at 11:15pm via com.aiia.vaultwatcher launchd agent
    (runs 15 min after obsidian_bridge export, so it picks up fresh exports
     AND any human edits made during the day)
"""

import hashlib
import json
import logging
import os
import re
import sys
import urllib.error
import urllib.request
from datetime import datetime
from pathlib import Path

# --- Paths & URLs ---

BRAIN_URL = os.getenv("AIIA_URL", "http://localhost:8100")
VAULT_DIR = Path(os.getenv("AIIA_VAULT", Path.home() / "AIIAVault"))
LOG_DIR = Path.home() / ".aiia" / "logs" / "vault"
STATE_FILE = LOG_DIR / "watcher_state.json"

LOG_DIR.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(name)s] %(levelname)s: %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(LOG_DIR / "watcher.log"),
    ],
)
logger = logging.getLogger("aiia.vault_watcher")


# --- Files to SKIP (AIIA-owned, auto-generated by obsidian_bridge + vault_writer) ---

AIIA_OWNED_FILES = frozenset(
    {
        "30-Decisions/AIIA-Decisions.md",
        "40-Sessions/AIIA-Sessions.md",
        "50-Stories/AIIA-Backlog.md",
        "80-Resources/AIIA-Patterns.md",
        "80-Resources/AIIA-Lessons.md",
    }
)

# Patterns for AIIA-generated cluster files (e.g., decisions-2026-04.md)
_CLUSTER_PATTERN = re.compile(
    r"^(decisions|patterns|lessons|sessions|team|project|agents|meta)-\d{4}-\d{2}\.md$"
)

# Directories that contain only AIIA-generated content — skip entirely
AIIA_OWNED_DIRS = frozenset({"85-Wiki"})

# Skip directories that aren't knowledge
SKIP_DIRS = frozenset(
    {
        ".obsidian",
        ".trash",
        "Templates",
        ".git",
        "processed",
    }
)


def _is_aiia_managed(file_path: Path) -> bool:
    """Check if a file has aiia_managed: true in frontmatter."""
    try:
        with open(file_path, encoding="utf-8") as f:
            first_line = f.readline().strip()
            if first_line != "---":
                return False
            for line in f:
                if line.strip() == "---":
                    break
                if line.strip().startswith("aiia_managed:") and "true" in line.lower():
                    return True
    except Exception:
        pass
    return False


# Max file size to ingest (skip huge files)
MAX_FILE_SIZE = 100_000  # 100KB — larger files are likely data dumps, not knowledge

# Max content length per ingest call (AIIA/ChromaDB limit)
MAX_CHUNK_SIZE = 8_000  # chars — chunk larger docs


# --- Structured extraction: which vault folders map to AIIA memory categories ---

MEMORY_MAPPING: dict[str, str] = {
    "30-Decisions": "decisions",
    "50-Stories": "project",
    "10-Daily": "sessions",
    "60-Clients": "project",
    "20-Workstreams": "project",
    "70-Areas": "patterns",
}


# ---------------------------------------------------------------------------
# HTTP helpers (stdlib only — no pip installs)
# ---------------------------------------------------------------------------


def _post(url: str, body: dict, timeout: int = 15) -> dict | None:
    """POST JSON to AIIA API, return parsed response or None on error."""
    data = json.dumps(body).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.URLError as e:
        logger.warning(f"Unreachable: {url} — {e}")
    except Exception as e:
        logger.warning(f"POST {url} failed: {e}")
    return None


def _get(url: str, timeout: int = 10) -> dict | None:
    """GET request returning parsed JSON, or None on any error."""
    try:
        with urllib.request.urlopen(url, timeout=timeout) as resp:
            return json.loads(resp.read().decode())
    except Exception as e:
        logger.warning(f"GET {url} failed: {e}")
    return None


# ---------------------------------------------------------------------------
# Incremental sync state (same pattern as obsidian_bridge.py)
# ---------------------------------------------------------------------------


class WatcherState:
    """Track SHA256 hashes of ingested files. Skip unchanged on next run."""

    def __init__(self, path: Path):
        self._path = path
        self._state: dict[str, str] = {}
        if path.exists():
            try:
                self._state = json.loads(path.read_text())
            except Exception:
                pass

    def is_changed(self, rel_path: str, content: str) -> bool:
        """Return True if file content has changed since last ingest."""
        h = hashlib.sha256(content.encode()).hexdigest()[:16]
        if self._state.get(rel_path) == h:
            return False
        self._state[rel_path] = h
        return True

    def remove(self, rel_path: str):
        """Remove a deleted file from state."""
        self._state.pop(rel_path, None)

    def save(self):
        self._path.write_text(json.dumps(self._state, indent=2, sort_keys=True))

    @property
    def tracked_count(self) -> int:
        return len(self._state)


# ---------------------------------------------------------------------------
# Vault scanner
# ---------------------------------------------------------------------------


def scan_vault(vault_dir: Path) -> list[tuple[str, Path]]:
    """
    Walk the vault and return (relative_path, full_path) for eligible .md files.
    Skips: AIIA-owned files, hidden dirs, Templates, files > MAX_FILE_SIZE.
    """
    results = []
    for root, dirs, files in os.walk(vault_dir):
        # Prune skip directories
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS and not d.startswith(".")]

        for fname in files:
            if not fname.endswith(".md"):
                continue

            full_path = Path(root) / fname
            rel_path = str(full_path.relative_to(vault_dir))

            # Skip AIIA-owned auto-generated files
            if rel_path in AIIA_OWNED_FILES:
                continue

            # Skip AIIA-owned directories (85-Wiki/)
            if any(rel_path.startswith(d + "/") for d in AIIA_OWNED_DIRS):
                continue

            # Skip AIIA cluster files (decisions-2026-04.md, etc.)
            if _CLUSTER_PATTERN.match(full_path.name):
                continue

            # Skip files with aiia_managed: true frontmatter
            if _is_aiia_managed(full_path):
                continue

            # Skip oversized files
            if full_path.stat().st_size > MAX_FILE_SIZE:
                logger.debug(f"Skipping oversized: {rel_path} ({full_path.stat().st_size} bytes)")
                continue

            results.append((rel_path, full_path))

    return sorted(results)


# ---------------------------------------------------------------------------
# Content processing
# ---------------------------------------------------------------------------


def _extract_title(content: str, filename: str) -> str:
    """Extract title from frontmatter or first heading, fallback to filename."""
    for line in content.split("\n"):
        line = line.strip()
        if line.startswith("# ") and not line.startswith("# ---"):
            return line[2:].strip()
    # Fallback: filename without extension
    return Path(filename).stem.replace("-", " ").replace("_", " ").title()


def _classify_doc(rel_path: str) -> tuple[str, str | None]:
    """
    Classify a vault file for AIIA ingestion.

    Returns (doc_type, memory_category):
    - doc_type: for ChromaDB indexing (e.g., "vault-daily", "vault-decision")
    - memory_category: if not None, also store as structured memory
    """
    parts = rel_path.split("/")
    folder = parts[0] if len(parts) > 1 else ""

    # Map folder to doc_type and optional memory category
    memory_cat = MEMORY_MAPPING.get(folder)

    type_map = {
        "10-Daily": "vault-daily",
        "20-Workstreams": "vault-workstream",
        "30-Decisions": "vault-decision",
        "40-Sessions": "vault-session",
        "50-Stories": "vault-story",
        "60-Clients": "vault-client",
        "70-Areas": "vault-area",
        "80-Resources": "vault-resource",
        "Content-Drafts": "vault-content",
    }

    doc_type = type_map.get(folder, "vault-note")
    return doc_type, memory_cat


def _chunk_content(text: str, max_size: int = MAX_CHUNK_SIZE) -> list[str]:
    """Split long content into chunks for ingestion. Splits at paragraph boundaries."""
    if len(text) <= max_size:
        return [text]

    chunks = []
    current = ""
    for para in text.split("\n\n"):
        if len(current) + len(para) + 2 > max_size:
            if current:
                chunks.append(current.strip())
            current = para
        else:
            current = current + "\n\n" + para if current else para

    if current.strip():
        chunks.append(current.strip())

    return chunks or [text[:max_size]]


def _extract_summary(content: str, max_len: int = 500) -> str:
    """Extract a summary from content for memory storage. Skip frontmatter."""
    lines = []
    in_frontmatter = False
    for line in content.split("\n"):
        if line.strip() == "---":
            in_frontmatter = not in_frontmatter
            continue
        if in_frontmatter:
            continue
        if line.strip() and not line.startswith(">"):
            lines.append(line.strip())

    text = " ".join(lines)
    if len(text) > max_len:
        text = text[:max_len].rsplit(" ", 1)[0] + "..."
    return text


# ---------------------------------------------------------------------------
# Ingest functions
# ---------------------------------------------------------------------------


def ingest_document(rel_path: str, content: str, doc_type: str) -> bool:
    """Ingest a vault document into AIIA's ChromaDB knowledge store."""
    title = _extract_title(content, rel_path)
    chunks = _chunk_content(content)

    success = True
    for i, chunk in enumerate(chunks):
        source = f"obsidian-vault:{rel_path}"
        if len(chunks) > 1:
            source += f":chunk-{i + 1}"

        result = _post(
            f"{BRAIN_URL}/v1/aiia/ingest",
            {
                "text": chunk,
                "source": source,
                "doc_type": doc_type,
                "metadata": {
                    "vault_path": rel_path,
                    "title": title,
                    "chunk": i + 1,
                    "total_chunks": len(chunks),
                    "synced_at": datetime.utcnow().isoformat(),
                },
            },
        )
        if not result:
            success = False
            break

    return success


def remember_fact(rel_path: str, content: str, category: str) -> bool:
    """Store a vault document as structured AIIA memory."""
    title = _extract_title(content, rel_path)
    summary = _extract_summary(content)

    if len(summary) < 20:
        return True  # Too short to be meaningful

    fact = f"[Obsidian: {title}] {summary}"

    result = _post(
        f"{BRAIN_URL}/v1/aiia/remember",
        {
            "fact": fact,
            "category": category,
            "source": "obsidian-vault",
            "metadata": {
                "vault_path": rel_path,
                "title": title,
            },
        },
    )
    return result is not None


# ---------------------------------------------------------------------------
# Main sync
# ---------------------------------------------------------------------------


def run_watcher(dry_run: bool = False, force: bool = False) -> dict:
    """
    Scan the vault, find changed files, ingest into AIIA.

    Args:
        dry_run: Log what would happen without making API calls.
        force: Ignore state hashes, re-ingest everything.

    Returns:
        Summary dict with counts.
    """
    logger.info(f"Vault Watcher starting — vault: {VAULT_DIR}, brain: {BRAIN_URL}")

    # Check AIIA is reachable
    if not dry_run:
        status = _get(f"{BRAIN_URL}/v1/aiia/status")
        if not status:
            logger.error("AIIA Brain API unreachable — aborting")
            return {"status": "error", "reason": "AIIA unreachable"}

    state = WatcherState(STATE_FILE)
    files = scan_vault(VAULT_DIR)
    logger.info(
        f"Found {len(files)} eligible vault files ({state.tracked_count} previously tracked)"
    )

    stats = {
        "scanned": len(files),
        "ingested": 0,
        "remembered": 0,
        "skipped_unchanged": 0,
        "errors": 0,
    }

    for rel_path, full_path in files:
        content = full_path.read_text(encoding="utf-8", errors="replace")

        # Skip if unchanged (unless forced)
        if not force and not state.is_changed(rel_path, content):
            stats["skipped_unchanged"] += 1
            continue

        doc_type, memory_cat = _classify_doc(rel_path)

        if dry_run:
            logger.info(
                f"  [DRY RUN] Would ingest: {rel_path} (type={doc_type}, memory={memory_cat})"
            )
            stats["ingested"] += 1
            continue

        # Ingest into ChromaDB knowledge store
        if ingest_document(rel_path, content, doc_type):
            stats["ingested"] += 1
            logger.info(f"  Ingested: {rel_path} (type={doc_type})")
        else:
            stats["errors"] += 1
            logger.error(f"  Failed to ingest: {rel_path}")
            continue

        # Also store as structured memory if applicable
        if memory_cat:
            if remember_fact(rel_path, content, memory_cat):
                stats["remembered"] += 1
                logger.info(f"  Remembered: {rel_path} → {memory_cat}")

    if not dry_run:
        state.save()

    # Summary
    logger.info(
        f"Vault Watcher complete: "
        f"{stats['ingested']} ingested, "
        f"{stats['remembered']} remembered, "
        f"{stats['skipped_unchanged']} unchanged, "
        f"{stats['errors']} errors"
    )

    return stats


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    dry_run = "--dry-run" in sys.argv
    force = "--force" in sys.argv

    if dry_run:
        logger.info("DRY RUN — no API calls will be made")

    result = run_watcher(dry_run=dry_run, force=force)
    print(json.dumps(result, indent=2))
